######################################################################
##
## Filename: simple_multiplexer_tb.udo
## Created on: Fri Sep 20 15:13:55 Romance Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
